[theme]
base= "light"
linkUnderline = false
primaryColor = "#56524D"
secondaryBackgroundColor = "#E4E4E4"
showWidgetBorder = true
borderColor = "#2B2523"
linkColor = "#76706C"
codeBackgroundColor = "#D4D4D4"
textColor = "#1F1916"
font = "serif"
dataframeBorderColor = "#2B2523"
dataframeHeaderBackgroundColor = "#D4D4D4"
chartCategoricalColors = ["#204F80", "#804F1F", "#0A2845", "#426F99", "#45280A", "#996F42"]

[theme.sidebar]
backgroundColor = "#D4D4D4"
primaryColor = "#56524D"
secondaryBackgroundColor = "#AAA39F"
textColor = "#1F1916"
borderColor = "#2B2523"
font = "serif"