# Google OAuth Configuration Example
# Copy this file to secrets.toml and replace placeholder values with your actual credentials

[auth]
# Redirect URI - must match exactly what's configured in Google Cloud Console
# This should be the URL where your Streamlit app will receive the OAuth callback
redirect_uri = "http://localhost:8501/oauth2callback"

# Cookie secret for session management - generate a random 32+ character string
# You can use: openssl rand -hex 32
# Or any random string generator
cookie_secret = "your-very-long-random-cookie-secret-string-here-12345"

# Google OAuth Client ID - get this from Google Cloud Console
# Format: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
client_id = "your-google-client-id-here.apps.googleusercontent.com"

# Google OAuth Client Secret - get this from Google Cloud Console
# Keep this secure and never share it publicly
client_secret = "your-google-client-secret-here"

# Google OpenID configuration - this is standard for Google OAuth
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

# Optional: Additional OAuth parameters
# client_kwargs = { "prompt" = "login" }  # Forces login prompt every time
